on:
  push:
    tags:
      - "v*"

name: release

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos]

    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Set git line endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - if: ${{ matrix.os == 'windows-latest '}}
        run: cp target/release/midi-ctrl.exe target/release/midi-ctrl-embedded.exe MidiCtrl.lrplugin
      - if: ${{ matrix.os != 'windows-latest '}}
        run: cp target/release/midi-ctrl target/release/midi-ctrl-embedded MidiCtrl.lrplugin
      - run: ./update_version "${GITHUB_REF#refs/*/}" > Info.lua
      - run: cp Info.lua MidiCtrl.lrplugin/Info.lua
      - env:
          MATRIXOS: ${{ matrix.os }}
        run: 7z a -tzip -y "MidiCtrl-$MATRIXOS.zip" MidiCtrl.lrplugin
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.zip"
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
