on:
  push:
    tags:
      - "v*"

name: release

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - if: ${{ matrix.os == 'windows-latest '}}
        run: cp target/release/midi-ctrl.exe MidiCtrl.lrplugin
      - if: ${{ matrix.os != 'windows-latest '}}
        run: cp target/release/midi-ctrl MidiCtrl.lrplugin
      - run: ./update_version > Info.lua
      - run: cp Info.lua MidiCtrl.lrplugin/Info.lua
      - run: zip -r9 MidiCtrl.zip MidiCtrl.lrplugin
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: MidiCtrl.zip
